var res = {
    bat_frames: "res/bat_frames.png",
    spritesheet_plist: "res/spritesheet.plist",
    spritesheet_png: "res/spritesheet.png",
    bgm_main: "res/mitehaikenai.mp3",
    bgm_title: "res/silen.mp3",
    player_png: "res/player.png",
    crate_png: "res/crate.png",
    warai: "res/warai.mp3",
    hell_bell: "res/hell_bell.mp3",
    egao: "res/egao.jpg",
    egao2: "res/egao2.png",
    soup: "res/soup.mp3",
    kage: "res/kage.png",
    sakebi: "res/sakebi.mp3",
    nanmanda: "res/nanmanda.mp3",
    hand: "res/hand.png",
    //ここからペイントマン
    title: "res/title.png",
    titleplay: "res/titleのプレイ.png",
    kabeblock: "res/壁ブロック1.png",
    paintmansiro1: "res/paintmansiro1.png",
    paintmansiro2: "res/paintmansiro2.png",
    paintmanaka1: "res/paintmanaka1.png",
    paintmanaka2: "res/paintmanaka2.png",
    paintmanao1: "res/paintmanao1.png",
    paintmanao2: "res/paintmanao2.png",
    paintmanki1: "res/paintmanki1.png",
    paintmanki2: "res/paintmanki2.png",
    paintmanmidori1: "res/paintmanmidori1.png",
    paintmanmidori2: "res/paintmanmidori2.png",
    paintmanmurasaki1: "res/paintmanmurasaki1.png",
    paintmanmurasaki2: "res/paintmanmurasaki2.png",
    hidari: "res/矢印左.png",
    migi: "res/矢印右.png",
    ue: "res/矢印前.png",
    sita: "res/矢印後.png",
    yuka: "res/床.png",
    dot: "res/取るドット.png",
    backsiro: "res/白背景.png",
    kinoback: "res/木背景.png",
    clear: "res/stageclear.png",
    tekimannakaao: "res/敵真ん中(青).png",
    tekiaomigi: "res/敵右手上げ(青).png",
    tekiaohidari: "res/敵左手上げ(青).png",
    tekiakamigi: "res/敵右手上げ(赤).png",
    tekiakahidari: "res/敵左手上げ(赤).png",
    tekikimigi: "res/敵右手上げ(黄).png",
    tekikihidari: "res/敵左手上げ(黄).png",
    tekimidorimigi: "res/敵右手上げ(緑).png",
    tekimidorihidari: "res/敵左手上げ(緑).png",
    tekimurasakimigi: "res/敵右手上げ(紫).png",
    tekimurasakihidari: "res/敵左手上げ(紫).png",
    tekimannakaaka: "res/敵真ん中(赤).png",
    tekimannakaki:"res/敵真ん中(黄).png",
    tekimannakamidori:"res/敵真ん中(緑).png",
    tekimannakamurasaki:"res/敵真ん中(紫).png",

    GAMEOVER: "res/GAMEOVER.png",
    iroyukaao: "res/色のついた床(青).png",
    iroyukaki: "res/色のついた床(黄).png",
    iroyukaaka: "res/色のついた床(赤).png",
    iroyukamidori: "res/色のついた床(緑).png",
    iroyukamurasaki: "res/色のついた床(紫).png",
    kakeru: "res/アスタリスク.png",
    suuji3: "res/数字の3.png",
    STAGE1: "res/STAGE1.png",
    stage2: "res/stage2.png",
    stage3: "res/stage3.png",
    SCORE: "res/SCORE.png",
    suuji0: "res/0.png",
    GO: "res/GO.png",
    stage4: "res/stage4.png",



};

var g_resources = [];
for (var i in res) {
    g_resources.push(res[i]);
}
